### ISSUE TITLE
Timeout cannot be set to 0

### ISSUE THREAD

**Issue by whitebird** [prestonp/simple-rcon#11]
When setting timeout to 0 (meaning no timeout), it reverts to the default 5 seconds timeout.
This is due to 0 meaning false on this line : https://github.com/prestonp/simple-rcon/blob/master/lib/rcon.js#L77

**Comment by prestonp** [comment]
Hey @whitebird [v0.3.1](https://github.com/prestonp/simple-rcon/releases/tag/v0.3.1) has been published on npm. Thanks!!!
