### ISSUE TITLE
UTF8 Support

### ISSUE THREAD

**Issue by garrettjoecox** [prestonp/simple-rcon#18]
Hey there,

@ lib/packet.js:13,24 you are encoding & decoding using `ASCII`, rather than the default `UTF8`. Are there any reasons behind this? This causes issues when sending any non ASCII characters through the RCON packets.

**Comment by skibz** [comment]
hi @garrettjoecox 

if you refer [here](https://developer.valvesoftware.com/wiki/Source_RCON_Protocol#Basic_Packet_Structure), the protocol prescribes the use of ascii encoding.

**Comment by garrettjoecox** [comment]
Ah gotcha, thanks.
